"""Website assessment report — compare your company to competitors."""

from sqlalchemy.orm import Session
from src.db.models import Company
from src.analysis.comparison import get_feature_matrix, get_marketing_comparison, identify_gaps
from src.analysis.targeting_matrix import build_targeting_matrix, format_matrix_text
from src.extraction.llm import call_claude


def generate_executive_summary(db: Session, my_company_id: int) -> str:
    """Generate an AI-powered executive summary comparing you vs competitors."""
    my_company = db.query(Company).get(my_company_id)
    if not my_company:
        return "Error: company not found."

    competitors = db.query(Company).filter(Company.id != my_company_id).all()
    gaps = identify_gaps(db, my_company_id)
    matrix = build_targeting_matrix(db)

    # Build context for Claude
    context = f"""Company: {my_company.name}
Description: {my_company.description}

Competitors: {', '.join(c.name for c in competitors)}

Feature gaps (features competitors have that we don't):
{gaps.get('missing_features', {})}

Unique features (features only we have):
{gaps.get('unique_features', {})}

Market gaps (verticals we don't target):
{gaps.get('market_gaps', [])}

Messaging gaps:
{gaps.get('messaging_gaps', [])}

Whitespace opportunities: {matrix.get('whitespace', [])}
"""

    prompt = f"""Based on the following competitive intelligence data, write a concise executive summary (3-5 paragraphs) for {my_company.name}'s leadership team.

{context}

The summary should:
1. State the overall competitive position
2. Highlight key strengths and advantages
3. Identify the most critical gaps to address
4. Recommend top 3 strategic priorities
5. Be direct and actionable — no fluff"""

    return call_claude(
        "You are a senior competitive strategy consultant writing a briefing for a C-suite audience.",
        prompt,
        max_tokens=2000,
    )


def generate_full_report(db: Session, my_company_id: int) -> str:
    """Generate a detailed markdown competitive assessment report."""
    my_company = db.query(Company).get(my_company_id)
    if not my_company:
        return "Error: company not found."

    competitors = db.query(Company).filter(Company.id != my_company_id).all()
    feature_matrix = get_feature_matrix(db)
    marketing = get_marketing_comparison(db)
    gaps = identify_gaps(db, my_company_id)
    targeting = build_targeting_matrix(db)

    # Build the report
    sections = []

    # Title
    sections.append(f"# Competitive Assessment: {my_company.name}\n")
    sections.append(f"*Generated by MarketLens*\n")

    # Executive Summary
    sections.append("## Executive Summary\n")
    summary = generate_executive_summary(db, my_company_id)
    sections.append(summary + "\n")

    # Company Overview
    sections.append("## Company Profiles\n")
    for company in [my_company] + competitors:
        tag = " *(Your Company)*" if company.id == my_company_id else ""
        sections.append(f"### {company.name}{tag}\n")
        sections.append(f"{company.description}\n")
        if company.product_intel:
            sections.append(f"**Positioning:** {company.product_intel.product_positioning}\n")
        sections.append("")

    # Feature Comparison
    sections.append("## Feature Comparison Matrix\n")
    categories = feature_matrix.get("categories", {})
    companies = feature_matrix.get("companies", [])
    for cat, features in categories.items():
        sections.append(f"### {cat}\n")
        header = "| Feature | " + " | ".join(companies) + " |"
        sep = "|" + "---|" * (len(companies) + 1)
        sections.append(header)
        sections.append(sep)
        for fname, presence in features.items():
            row = f"| {fname} | " + " | ".join("✅" if presence.get(c) else "❌" for c in companies) + " |"
            sections.append(row)
        sections.append("")

    # Marketing Comparison
    sections.append("## Marketing & Messaging\n")
    for cname, data in marketing.items():
        sections.append(f"### {cname}\n")
        if data["value_propositions"]:
            sections.append("**Value Propositions:**")
            for vp in data["value_propositions"]:
                sections.append(f"- {vp}")
        if data["differentiators"]:
            sections.append("\n**Differentiators:**")
            for d in data["differentiators"]:
                sections.append(f"- {d}")
        if data["tone"]:
            sections.append(f"\n**Tone:** {data['tone']}")
        sections.append("")

    # Gaps
    sections.append("## Gap Analysis\n")
    if gaps.get("missing_features"):
        sections.append("### Features You're Missing\n")
        for cat, feats in gaps["missing_features"].items():
            sections.append(f"**{cat}:** {', '.join(feats)}")
        sections.append("")

    if gaps.get("unique_features"):
        sections.append("### Your Unique Features\n")
        for cat, feats in gaps["unique_features"].items():
            sections.append(f"**{cat}:** {', '.join(feats)}")
        sections.append("")

    if gaps.get("market_gaps"):
        sections.append("### Market Gaps\n")
        sections.append(f"Verticals targeted by competitors but not you: {', '.join(gaps['market_gaps'])}\n")

    # Targeting Matrix
    sections.append("## Market Targeting Matrix\n")
    sections.append("```")
    sections.append(format_matrix_text(targeting))
    sections.append("```\n")

    # Recommendations (AI-generated)
    sections.append("## Recommendations\n")
    rec_prompt = f"""Based on this competitive data for {my_company.name}:

Missing features: {gaps.get('missing_features', {})}
Market gaps: {gaps.get('market_gaps', [])}
Messaging gaps: {gaps.get('messaging_gaps', [])}
Unique strengths: {gaps.get('unique_features', {})}

Write 5-7 specific, actionable recommendations. Each should have a title and 2-3 sentence explanation. Format as markdown list."""

    recommendations = call_claude(
        "You are a competitive strategy consultant.",
        rec_prompt,
        max_tokens=2000,
    )
    sections.append(recommendations)

    return "\n".join(sections)
